version: '3.9'
services:
  postgres:
    image: postgres:14.7
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      LOG_LEVEL: ${LOG_LEVEL}
      DEBUG_MODE: ${DEBUG_MODE}
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/app/node_modules
      - .env:/app/.env
  frontend:
    build:
      context: ./src/frontend/app
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3000
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      NEXT_PUBLIC_SENTRY_DSN: ${SENTRY_DSN}
      NEXTAUTH_URL: http://frontend:3001
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    ports:
      - "3001:3001"
    volumes:
      - node_modules:/app/node_modules
      - .env:/app/.env
volumes:
  postgres_data:
  node_modules: